"""The conflict catalogue, read from the artefact `src/schema` generates.

`build.py` used to hold its own `DEFAULTS` and `CONFLICT_NAMES`, and
`src/scoring/src/probe.ts` held the same settings again with the plausibility
ceilings and the cosmetic/structural labels beside them. Two copies of the same
facts on opposite sides of the TypeScript/Python seam is exactly the
arrangement that drifts, and P1M1 needs a third consumer — the projection
generator — which would have made it three.

`contract/catalogue.json` is generated by `npm run contract:generate` and CI
checks it for drift, the same arrangement the OpenAPI documents already use.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

_CATALOGUE_PATH = Path(__file__).resolve().parents[2] / "contract" / "catalogue.json"


@dataclass(frozen=True)
class Setting:
    """One way an operator can depart from publishing honestly."""

    conflict: str
    section: str
    group: str
    key: str
    off: object
    cosmetic: bool
    structural: bool
    generate: tuple[object, ...]
    plausible_max: object | None
    plausible_because: str | None
    excludes: tuple[str, ...]

    def is_plausible(self, value: object) -> bool:
        """Whether a value stays inside what two real operators could differ by."""
        if self.plausible_max is None:
            return True
        if isinstance(self.plausible_max, (int, float)) and isinstance(value, (int, float)):
            # Precision counts down: fewer decimal places is the stronger conflict.
            if self.key == "precision":
                return value >= self.plausible_max
            return value <= self.plausible_max
        return value == self.plausible_max


@dataclass(frozen=True)
class DisruptionPolicy:
    """How much goes wrong, and how much warning there is.

    Read from the contract rather than restated here. `notice_lead_min_s` is the
    one the generator needs: a staleness setting at or below it conceals nothing
    on any operator, however the conflict is placed (`KNOWN-ISSUES.md` #19).
    """

    delay_rate: float
    cancellation_rate: float
    delay_range_s: tuple[int, int]
    notice_lead_s: tuple[int, int]

    @property
    def notice_lead_min_s(self) -> int:
        return self.notice_lead_s[0]


@dataclass(frozen=True)
class Catalogue:
    settings: tuple[Setting, ...]
    tier_sections: dict[int, tuple[str, ...]]
    tier_cosmetic_only: tuple[int, ...]
    policy: DisruptionPolicy

    def defaults(self) -> dict[str, dict[str, object]]:
        """A conflict-free manifest: every setting at its `off` value."""
        out: dict[str, dict[str, object]] = {}
        for s in self.settings:
            out.setdefault(s.group, {})[s.key] = s.off
        return out

    def conflict_names(self) -> dict[tuple[str, str], str]:
        return {(s.group, s.key): s.conflict for s in self.settings}

    def for_tier(self, tier: int) -> tuple[Setting, ...]:
        """The settings a world of this tier may activate."""
        sections = self.tier_sections.get(tier, ())
        cosmetic_only = tier in self.tier_cosmetic_only
        return tuple(
            s for s in self.settings if s.section in sections and (s.cosmetic or not cosmetic_only)
        )


@lru_cache(maxsize=1)
def load() -> Catalogue:
    if not _CATALOGUE_PATH.exists():
        raise FileNotFoundError(
            f"{_CATALOGUE_PATH} is missing. Generate it: npm run contract:generate"
        )
    raw = json.loads(_CATALOGUE_PATH.read_text(encoding="utf-8"))
    settings = tuple(
        Setting(
            conflict=s["conflict"],
            section=s["section"],
            group=s["group"],
            key=s["key"],
            off=s["off"],
            cosmetic=bool(s.get("cosmetic", False)),
            structural=bool(s.get("structural", False)),
            generate=tuple(s.get("generate", ())),
            plausible_max=(s.get("plausible") or {}).get("max"),
            plausible_because=(s.get("plausible") or {}).get("because"),
            excludes=tuple(s.get("excludes", ())),
        )
        for s in raw["settings"]
    )
    pol = raw["disruption_policy"]
    return Catalogue(
        settings=settings,
        tier_sections={int(k): tuple(v) for k, v in raw["tier_sections"].items()},
        tier_cosmetic_only=tuple(raw["tier_cosmetic_only"]),
        policy=DisruptionPolicy(
            delay_rate=pol["delayRate"],
            cancellation_rate=pol["cancellationRate"],
            delay_range_s=tuple(pol["delayRangeS"]),
            notice_lead_s=tuple(pol["noticeLeadS"]),
        ),
    )
