"""The conflict catalogue, read from the artefact `src/schema` generates.

`build.py` used to hold its own `DEFAULTS` and `CONFLICT_NAMES`, and
`src/scoring/src/probe.ts` held the same settings again with the plausibility
ceilings and the cosmetic/structural labels beside them. Two copies of the same
facts on opposite sides of the TypeScript/Python seam is exactly the
arrangement that drifts, and P1M1 needs a third consumer — the projection
generator — which would have made it three.

`contract/catalogue.json` is generated by `npm run contract:generate` and CI
checks it for drift, the same arrangement the OpenAPI documents already use.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

_CATALOGUE_PATH = Path(__file__).resolve().parents[2] / "contract" / "catalogue.json"


@dataclass(frozen=True)
class Setting:
    """One way an operator can depart from publishing honestly."""

    conflict: str
    section: str
    group: str
    key: str
    off: object
    cosmetic: bool
    structural: bool
    generate: tuple[object, ...]
    plausible_max: object | None
    plausible_because: str | None
    excludes: tuple[str, ...]
    #: `generate` holds kinds rather than severities, so a stronger world must
    #: not prefer its later entries. See the field's note in
    #: `src/schema/src/catalogue.ts` and `KNOWN-ISSUES.md` #48.
    categorical: bool = False
    #: In the catalogue — audited, answerable, measurable — and never placed by
    #: the generator. See the field's note in `src/schema/src/catalogue.ts` and
    #: `KNOWN-ISSUES.md` #57.
    drawn: bool = True

    def is_plausible(self, value: object) -> bool:
        """Whether a value stays inside what two real operators could differ by."""
        if self.plausible_max is None:
            return True
        if isinstance(self.plausible_max, (int, float)) and isinstance(value, (int, float)):
            # Precision counts down: fewer decimal places is the stronger conflict.
            if self.key == "precision":
                return value >= self.plausible_max
            return value <= self.plausible_max
        return value == self.plausible_max


@dataclass(frozen=True)
class DisruptionPolicy:
    """How much goes wrong, and how much warning there is.

    Read from the contract rather than restated here. `notice_lead_min_s` is the
    one the generator needs: a staleness setting at or below it conceals nothing
    on any operator, however the conflict is placed (`KNOWN-ISSUES.md` #19).
    """

    delay_rate: float
    cancellation_rate: float
    delay_range_s: tuple[int, int]
    notice_lead_s: tuple[int, int]

    @property
    def notice_lead_min_s(self) -> int:
        return self.notice_lead_s[0]


@dataclass(frozen=True)
class RungWorld:
    """The city a rung asks for (`src/schema/src/ladder.ts`)."""

    arms: int
    sites_per_arm: int
    hub_quays: int
    chords: int
    regional_lines: int
    metro_lines: int
    roster: tuple[str, ...]
    max_reach_share: float
    #: Each radial line's headway in seconds, cycled over the radials in order.
    #: See the field's note in `src/schema/src/ladder.ts` (`KNOWN-ISSUES.md` #61).
    radial_headways_s: tuple[int, ...]


@dataclass(frozen=True)
class Shape:
    """A kind of place, which is the axis that is *not* the tier.

    Scale is ordered and shape is not: one city and three towns joined by rail
    are different problems rather than different amounts of one
    (`src/schema/src/shape.ts`).
    """

    id: str
    name: str
    centres: int
    centre_spacing_m: float
    #: How the towns are joined: "rail", "bus", or "both".
    link: str


@dataclass(frozen=True)
class Rung:
    """One rung of the ladder, read from the contract.

    **The tier is the index and the id is the identity.** The numbering is
    expected to move — six rungs may become nine — and a result recorded against
    "tier 4" is uninterpretable afterwards unless it also says which rung that
    was. See `src/schema/src/ladder.ts`.
    """

    id: str
    name: str
    sections: tuple[str, ...]
    cosmetic_only: bool
    quota: dict[str, int]
    density: float
    world: RungWorld
    #: How many dirty operators publish time with no offset, or `None` to leave it
    #: to the draw. See the field's note in `src/schema/src/ladder.ts`.
    offsetless: int | None = None


@dataclass(frozen=True)
class Catalogue:
    settings: tuple[Setting, ...]
    policy: DisruptionPolicy
    #: The ladder, in order. Every tier-keyed view below is derived from it, so
    #: inserting a rung is one entry in `ladder.ts` and nothing here
    #: (`ROADMAP.md` P1M5).
    rungs: tuple[Rung, ...]
    #: Bumped when the ladder changes in a way that makes recorded results
    #: incomparable. Written into every bundle beside the numeric tier.
    ladder_version: int
    #: The shapes a world may have, by id.
    shapes: tuple[Shape, ...] = ()

    def shape(self, shape_id: str) -> Shape | None:
        """The shape with this id, or `None` — never a default."""
        return next((s for s in self.shapes if s.id == shape_id), None)

    @property
    def tier_sections(self) -> dict[int, tuple[str, ...]]:
        return {i: r.sections for i, r in enumerate(self.rungs)}

    @property
    def tier_cosmetic_only(self) -> tuple[int, ...]:
        return tuple(i for i, r in enumerate(self.rungs) if r.cosmetic_only)

    @property
    def tier_quota(self) -> dict[int, dict[str, int]]:
        """How many settings from each section a dirty operator departs on.

        A tier is a *composition*, not a density (`KNOWN-ISSUES.md` #42).
        """
        return {i: r.quota for i, r in enumerate(self.rungs)}

    @property
    def tier_density(self) -> dict[int, float]:
        return {i: r.density for i, r in enumerate(self.rungs)}

    def rung_at(self, tier: int) -> Rung | None:
        """The rung at a tier, or `None` — never a default, which hides a typo."""
        return self.rungs[tier] if 0 <= tier < len(self.rungs) else None

    def defaults(self) -> dict[str, dict[str, object]]:
        """A conflict-free manifest: every setting at its `off` value."""
        out: dict[str, dict[str, object]] = {}
        for s in self.settings:
            out.setdefault(s.group, {})[s.key] = s.off
        return out

    def conflict_names(self) -> dict[tuple[str, str], str]:
        return {(s.group, s.key): s.conflict for s in self.settings}

    def for_tier(self, tier: int) -> tuple[Setting, ...]:
        """The settings a world of this tier may activate."""
        sections = self.tier_sections.get(tier, ())
        cosmetic_only = tier in self.tier_cosmetic_only
        return tuple(
            s for s in self.settings if s.section in sections and (s.cosmetic or not cosmetic_only)
        )


@lru_cache(maxsize=1)
def load() -> Catalogue:
    if not _CATALOGUE_PATH.exists():
        raise FileNotFoundError(
            f"{_CATALOGUE_PATH} is missing. Generate it: npm run contract:generate"
        )
    raw = json.loads(_CATALOGUE_PATH.read_text(encoding="utf-8"))
    settings = tuple(
        Setting(
            conflict=s["conflict"],
            section=s["section"],
            group=s["group"],
            key=s["key"],
            off=s["off"],
            cosmetic=bool(s.get("cosmetic", False)),
            structural=bool(s.get("structural", False)),
            generate=tuple(s.get("generate", ())),
            plausible_max=(s.get("plausible") or {}).get("max"),
            plausible_because=(s.get("plausible") or {}).get("because"),
            excludes=tuple(s.get("excludes", ())),
            categorical=bool(s.get("categorical", False)),
            drawn=bool(s.get("drawn", True)),
        )
        for s in raw["settings"]
    )
    pol = raw["disruption_policy"]
    rungs = tuple(
        Rung(
            id=r["id"],
            name=r["name"],
            sections=tuple(r["sections"]),
            cosmetic_only=bool(r.get("cosmeticOnly", False)),
            quota={sec: int(n) for sec, n in r["quota"].items()},
            density=float(r["density"]),
            offsetless=None if r.get("offsetless") is None else int(r["offsetless"]),
            world=RungWorld(
                arms=int(r["world"]["arms"]),
                sites_per_arm=int(r["world"]["sitesPerArm"]),
                hub_quays=int(r["world"]["hubQuays"]),
                chords=int(r["world"]["chords"]),
                regional_lines=int(r["world"]["regionalLines"]),
                metro_lines=int(r["world"]["metroLines"]),
                roster=tuple(r["world"]["roster"]),
                max_reach_share=float(r["world"]["maxReachShare"]),
                radial_headways_s=tuple(int(v) for v in r["world"]["radialHeadwaysS"]),
            ),
        )
        for r in raw["ladder"]
    )
    return Catalogue(
        settings=settings,
        rungs=rungs,
        ladder_version=int(raw["ladder_version"]),
        shapes=tuple(
            Shape(
                id=x["id"],
                name=x["name"],
                centres=int(x["centres"]),
                centre_spacing_m=float(x["centreSpacingM"]),
                link=str(x["link"]),
            )
            for x in raw.get("shapes", ())
        ),
        policy=DisruptionPolicy(
            delay_rate=pol["delayRate"],
            cancellation_rate=pol["cancellationRate"],
            delay_range_s=tuple(pol["delayRangeS"]),
            notice_lead_s=tuple(pol["noticeLeadS"]),
        ),
    )
